//------------------------------------------------------------------------------
//     This code was generated by a tool (Visual Studio Resgen).
//------------------------------------------------------------------------------

namespace OnlineStore.Libraries.Language
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message
    {
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() { }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.Libraries.Language.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string MSG_ERROR_001
        {
            get 
            {
                return ResourceManager.GetString("MSG_ERROR_001", resourceCulture);
            }
        }

        public static string MSG_ERROR_002
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_002", resourceCulture);
            }
        }

        public static string MSG_ERROR_003
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_003", resourceCulture);
            }
        }

        public static string MSG_ERROR_004
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_004", resourceCulture);
            }
        }

        public static string MSG_ERROR_005
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_005", resourceCulture);
            }
        }

        public static string MSG_ERROR_006
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_006", resourceCulture);
            }
        }

        public static string MSG_ERROR_007
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_007", resourceCulture);
            }
        }

        public static string MSG_ERROR_008
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_008", resourceCulture);
            }
        }

        public static string MSG_ERROR_009
        {
            get
            {
                return ResourceManager.GetString("MSG_ERROR_009", resourceCulture);
            }
        }

        public static string MSG_OK_001
        {
            get
            {
                return ResourceManager.GetString("MSG_OK_001", resourceCulture);
            }
        }

        public static string MSG_OK_002
        {
            get
            {
                return ResourceManager.GetString("MSG_OK_002", resourceCulture);
            }
        }

        public static string MSG_OK_003
        {
            get
            {
                return ResourceManager.GetString("MSG_OK_003", resourceCulture);
            }
        }
    }
}